name: Compatibility Check

on:
  schedule:
    - cron: '0 0 * * 0' # Weekly
  workflow_dispatch:

jobs:
  check:
    runs-on: macos-latest
    strategy:
      matrix:
        xcode: ['14.3', '15.0']
    name: Xcode ${{ matrix.xcode }}
    
    steps:
    - uses: actions/checkout@v4
      
    - name: Setup Xcode ${{ matrix.xcode }}
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${{ matrix.xcode }}
        
    - name: Build
      run: |
        pod install
        xcodebuild build -workspace VPNclientEngineIOS.xcworkspace -scheme VPNclientEngineIOS -destination 'generic/platform=iOS'
