name: Lint

on: [push, pull_request]

jobs:
  swiftlint:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
      
    - name: Install SwiftLint
      run: brew install swiftlint
      
    - name: Run SwiftLint
      run: swiftlint --strict