name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
        
    - name: Install CocoaPods
      run: pod install --repo-update
      
    - name: Create XCFramework
      run: |
        xcodebuild archive \
          -workspace VPNclientEngine.xcworkspace \
          -scheme VPNclientEngine \
          -destination "generic/platform=iOS" \
          -archivePath "build/VPNclientEngineIOS" \
          SKIP_INSTALL=NO \
          BUILD_LIBRARY_FOR_DISTRIBUTION=YES
          
        xcodebuild archive \
          -workspace VPNclientEngine.xcworkspace \
          -scheme VPNclientEngine \
          -destination "generic/platform=iOS Simulator" \
          -archivePath "build/VPNclientEngine-Simulator" \
          SKIP_INSTALL=NO \
          BUILD_LIBRARY_FOR_DISTRIBUTION=YES
          
        xcodebuild -create-xcframework \
          -framework "build/VPNclientEngineIOS.xcarchive/Products/Library/Frameworks/VPNclientEngineIOS.framework" \
          -framework "build/VPNclientEngineSimulator.xcarchive/Products/Library/Frameworks/VPNclientEngineIOS.framework" \
          -output "VPNclientEngineIOS.xcframework"
          
    - name: Zip XCFramework
      run: zip -r VPNclientEngineIOS.xcframework.zip VPNclientEngine.xcframework
      
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: VPNclientEngine.xcframework.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}